
# ---------------------------------------------------------
# Base image
# ---------------------------------------------------------
FROM node:22-alpine

# ---------------------------------------------------------
# Application directory
# ---------------------------------------------------------
WORKDIR /app

# ---------------------------------------------------------
# Install dependencies first
# This improves Docker layer caching.
# ---------------------------------------------------------
COPY package*.json ./

RUN npm ci --omit=dev

# ---------------------------------------------------------
# Copy application source
# ---------------------------------------------------------
COPY . .

# ---------------------------------------------------------
# Application ports
#
# 4000, 4001, 4002, 4003 -> Express replicas
# 8000              -> Reverse proxy
# ---------------------------------------------------------
EXPOSE 4000 4001 8000

# ---------------------------------------------------------
# Make startup script executable
# ---------------------------------------------------------
RUN chmod +x app.process.sh

# ---------------------------------------------------------
# Start Express backend + reverse proxy
# ---------------------------------------------------------
CMD ["./app.process.sh"]

# docker buildx build --platform linux/arm64 -f dockerFile -t bhandekunal16/smtp-service:0.0.2-arm64 --push 

# sudo docker run -d   --name smtp-service   --restart unless-stopped   -p 8000:8000 bhandekunal16/smtp-service:0.0.2-arm64
